using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace SbaCars.Catalog.Infrastructure.Migrations;

/// <inheritdoc />
public partial class AddRebusOutbox : Migration
{
    /// <inheritdoc />
    protected override void Up(MigrationBuilder migrationBuilder)
    {
        migrationBuilder.Sql(
            """
            CREATE TABLE catalog.outbox
            (
              "Id" BIGINT GENERATED BY DEFAULT AS IDENTITY,
              "CorrelationId" VARCHAR(16) NULL,
              "MessageId" VARCHAR(255) NULL,
              "SourceQueue" VARCHAR(255) NULL,
              "DestinationAddress" VARCHAR(255) NOT NULL,
              "Headers" TEXT NULL,
              "Body" BYTEA NULL,
              "Sent" BOOLEAN NOT NULL DEFAULT(FALSE),
              PRIMARY KEY ("Id")
            );
            """);
    }

    /// <inheritdoc />
    protected override void Down(MigrationBuilder migrationBuilder)
    {
        migrationBuilder.Sql("DROP TABLE catalog.outbox;");
    }
}
