// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using SbaCars.Inventory.Infrastructure;

#nullable disable

namespace SbaCars.Inventory.Infrastructure.Migrations
{
    [DbContext(typeof(InventoryDbContext))]
    [Migration("20260817121207_AddSolicitacao")]
    partial class AddSolicitacao
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("inventory")
                .HasAnnotation("ProductVersion", "10.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("SbaCars.Inventory.Domain.Ofertas.Oferta", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("AtualizadoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("atualizado_em");

                    b.Property<DateTimeOffset>("CriadaEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("criada_em");

                    b.Property<string>("MotivoSuspensao")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("motivo_suspensao");

                    b.Property<string>("Situacao")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("situacao");

                    b.Property<DateTimeOffset?>("SuspensaEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("suspensa_em");

                    b.Property<uint>("xmin")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id")
                        .HasName("pk_oferta");

                    b.HasIndex("Situacao", "AtualizadoEm")
                        .HasDatabaseName("ix_oferta_situacao_atualizado_em");

                    b.ToTable("oferta", "inventory");
                });

            modelBuilder.Entity("SbaCars.Inventory.Domain.Solicitacoes.Solicitacao", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("AbertaEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("aberta_em");

                    b.Property<string>("Justificativa")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("justificativa");

                    b.Property<long?>("NovoPrecoCentavos")
                        .HasColumnType("bigint")
                        .HasColumnName("novo_preco_centavos");

                    b.Property<Guid>("OfertaId")
                        .HasColumnType("uuid")
                        .HasColumnName("oferta_id");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("status");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("tipo");

                    b.Property<uint>("xmin")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id")
                        .HasName("pk_solicitacao");

                    b.HasIndex("OfertaId", "Tipo")
                        .IsUnique()
                        .HasDatabaseName("ux_solicitacao_oferta_tipo_pendente")
                        .HasFilter("status = 'Pendente'");

                    b.HasIndex("Status", "AbertaEm")
                        .HasDatabaseName("ix_solicitacao_status_aberta_em");

                    b.ToTable("solicitacao", "inventory");
                });

            modelBuilder.Entity("SbaCars.Inventory.Domain.Ofertas.Oferta", b =>
                {
                    b.OwnsOne("SbaCars.Inventory.Domain.Ofertas.Disponibilidade", "Disponibilidade", b1 =>
                        {
                            b1.Property<Guid>("OfertaId")
                                .HasColumnType("uuid")
                                .HasColumnName("id");

                            b1.Property<DateTimeOffset>("Desde")
                                .HasColumnType("timestamp with time zone")
                                .HasColumnName("disponibilidade_desde");

                            b1.Property<string>("Estado")
                                .IsRequired()
                                .HasMaxLength(20)
                                .HasColumnType("character varying(20)")
                                .HasColumnName("disponibilidade_estado");

                            b1.Property<bool>("EstadoConhecido")
                                .HasColumnType("boolean")
                                .HasColumnName("disponibilidade_estado_conhecido");

                            b1.HasKey("OfertaId");

                            b1.ToTable("oferta", "inventory");

                            b1.WithOwner()
                                .HasForeignKey("OfertaId")
                                .HasConstraintName("fk_oferta_oferta_id");

                            b1.OwnsOne("SbaCars.Inventory.Domain.Ofertas.Autoria", "AlteradaPor", b2 =>
                                {
                                    b2.Property<Guid>("DisponibilidadeOfertaId")
                                        .HasColumnType("uuid")
                                        .HasColumnName("id");

                                    b2.Property<DateTimeOffset>("Em")
                                        .HasColumnType("timestamp with time zone")
                                        .HasColumnName("disponibilidade_alterada_por_em");

                                    b2.Property<string>("Nome")
                                        .IsRequired()
                                        .HasMaxLength(200)
                                        .HasColumnType("character varying(200)")
                                        .HasColumnName("disponibilidade_alterada_por_nome");

                                    b2.Property<string>("UsuarioId")
                                        .IsRequired()
                                        .HasMaxLength(200)
                                        .HasColumnType("character varying(200)")
                                        .HasColumnName("disponibilidade_alterada_por_usuario_id");

                                    b2.HasKey("DisponibilidadeOfertaId");

                                    b2.ToTable("oferta", "inventory");

                                    b2.WithOwner()
                                        .HasForeignKey("DisponibilidadeOfertaId")
                                        .HasConstraintName("fk_oferta_oferta_id");
                                });

                            b1.Navigation("AlteradaPor")
                                .IsRequired();
                        });

                    b.OwnsOne("SbaCars.Inventory.Domain.Ofertas.FatosConhecidos", "Fatos", b1 =>
                        {
                            b1.Property<Guid>("OfertaId")
                                .HasColumnType("uuid")
                                .HasColumnName("id");

                            b1.HasKey("OfertaId");

                            b1.ToTable("oferta", "inventory");

                            b1.WithOwner()
                                .HasForeignKey("OfertaId")
                                .HasConstraintName("fk_oferta_oferta_id");

                            b1.OwnsOne("SbaCars.Inventory.Domain.Ofertas.BlocoFato", "Condicao", b2 =>
                                {
                                    b2.Property<Guid>("FatosConhecidosOfertaId")
                                        .HasColumnType("uuid")
                                        .HasColumnName("id");

                                    b2.Property<string>("Descricao")
                                        .HasMaxLength(2000)
                                        .HasColumnType("character varying(2000)")
                                        .HasColumnName("fato_condicao_descricao");

                                    b2.Property<string>("Fonte")
                                        .HasMaxLength(300)
                                        .HasColumnType("character varying(300)")
                                        .HasColumnName("fato_condicao_fonte");

                                    b2.Property<bool>("Indisponivel")
                                        .HasColumnType("boolean")
                                        .HasColumnName("fato_condicao_indisponivel");

                                    b2.Property<string>("LimitacaoDeclarada")
                                        .HasMaxLength(1000)
                                        .HasColumnType("character varying(1000)")
                                        .HasColumnName("fato_condicao_limitacao");

                                    b2.Property<string>("Tipo")
                                        .IsRequired()
                                        .HasColumnType("text")
                                        .HasColumnName("fato_condicao_tipo");

                                    b2.HasKey("FatosConhecidosOfertaId");

                                    b2.ToTable("oferta", "inventory");

                                    b2.WithOwner()
                                        .HasForeignKey("FatosConhecidosOfertaId")
                                        .HasConstraintName("fk_oferta_oferta_id");

                                    b2.OwnsOne("SbaCars.Inventory.Domain.Ofertas.Autoria", "AtualizadoPor", b3 =>
                                        {
                                            b3.Property<Guid>("BlocoFatoFatosConhecidosOfertaId")
                                                .HasColumnType("uuid")
                                                .HasColumnName("id");

                                            b3.Property<DateTimeOffset>("Em")
                                                .HasColumnType("timestamp with time zone")
                                                .HasColumnName("fato_condicao_atualizado_por_em");

                                            b3.Property<string>("Nome")
                                                .IsRequired()
                                                .HasMaxLength(200)
                                                .HasColumnType("character varying(200)")
                                                .HasColumnName("fato_condicao_atualizado_por_nome");

                                            b3.Property<string>("UsuarioId")
                                                .IsRequired()
                                                .HasMaxLength(200)
                                                .HasColumnType("character varying(200)")
                                                .HasColumnName("fato_condicao_atualizado_por_usuario_id");

                                            b3.HasKey("BlocoFatoFatosConhecidosOfertaId");

                                            b3.ToTable("oferta", "inventory");

                                            b3.WithOwner()
                                                .HasForeignKey("BlocoFatoFatosConhecidosOfertaId")
                                                .HasConstraintName("fk_oferta_oferta_id");
                                        });

                                    b2.Navigation("AtualizadoPor")
                                        .IsRequired();
                                });

                            b1.OwnsOne("SbaCars.Inventory.Domain.Ofertas.BlocoFato", "Historico", b2 =>
                                {
                                    b2.Property<Guid>("FatosConhecidosOfertaId")
                                        .HasColumnType("uuid")
                                        .HasColumnName("id");

                                    b2.Property<string>("Descricao")
                                        .HasMaxLength(2000)
                                        .HasColumnType("character varying(2000)")
                                        .HasColumnName("fato_historico_descricao");

                                    b2.Property<string>("Fonte")
                                        .HasMaxLength(300)
                                        .HasColumnType("character varying(300)")
                                        .HasColumnName("fato_historico_fonte");

                                    b2.Property<bool>("Indisponivel")
                                        .HasColumnType("boolean")
                                        .HasColumnName("fato_historico_indisponivel");

                                    b2.Property<string>("LimitacaoDeclarada")
                                        .HasMaxLength(1000)
                                        .HasColumnType("character varying(1000)")
                                        .HasColumnName("fato_historico_limitacao");

                                    b2.Property<string>("Tipo")
                                        .IsRequired()
                                        .HasColumnType("text")
                                        .HasColumnName("fato_historico_tipo");

                                    b2.HasKey("FatosConhecidosOfertaId");

                                    b2.ToTable("oferta", "inventory");

                                    b2.WithOwner()
                                        .HasForeignKey("FatosConhecidosOfertaId")
                                        .HasConstraintName("fk_oferta_oferta_id");

                                    b2.OwnsOne("SbaCars.Inventory.Domain.Ofertas.Autoria", "AtualizadoPor", b3 =>
                                        {
                                            b3.Property<Guid>("BlocoFatoFatosConhecidosOfertaId")
                                                .HasColumnType("uuid")
                                                .HasColumnName("id");

                                            b3.Property<DateTimeOffset>("Em")
                                                .HasColumnType("timestamp with time zone")
                                                .HasColumnName("fato_historico_atualizado_por_em");

                                            b3.Property<string>("Nome")
                                                .IsRequired()
                                                .HasMaxLength(200)
                                                .HasColumnType("character varying(200)")
                                                .HasColumnName("fato_historico_atualizado_por_nome");

                                            b3.Property<string>("UsuarioId")
                                                .IsRequired()
                                                .HasMaxLength(200)
                                                .HasColumnType("character varying(200)")
                                                .HasColumnName("fato_historico_atualizado_por_usuario_id");

                                            b3.HasKey("BlocoFatoFatosConhecidosOfertaId");

                                            b3.ToTable("oferta", "inventory");

                                            b3.WithOwner()
                                                .HasForeignKey("BlocoFatoFatosConhecidosOfertaId")
                                                .HasConstraintName("fk_oferta_oferta_id");
                                        });

                                    b2.Navigation("AtualizadoPor")
                                        .IsRequired();
                                });

                            b1.OwnsOne("SbaCars.Inventory.Domain.Ofertas.BlocoFato", "Origem", b2 =>
                                {
                                    b2.Property<Guid>("FatosConhecidosOfertaId")
                                        .HasColumnType("uuid")
                                        .HasColumnName("id");

                                    b2.Property<string>("Descricao")
                                        .HasMaxLength(2000)
                                        .HasColumnType("character varying(2000)")
                                        .HasColumnName("fato_origem_descricao");

                                    b2.Property<string>("Fonte")
                                        .HasMaxLength(300)
                                        .HasColumnType("character varying(300)")
                                        .HasColumnName("fato_origem_fonte");

                                    b2.Property<bool>("Indisponivel")
                                        .HasColumnType("boolean")
                                        .HasColumnName("fato_origem_indisponivel");

                                    b2.Property<string>("LimitacaoDeclarada")
                                        .HasMaxLength(1000)
                                        .HasColumnType("character varying(1000)")
                                        .HasColumnName("fato_origem_limitacao");

                                    b2.Property<string>("Tipo")
                                        .IsRequired()
                                        .HasColumnType("text")
                                        .HasColumnName("fato_origem_tipo");

                                    b2.HasKey("FatosConhecidosOfertaId");

                                    b2.ToTable("oferta", "inventory");

                                    b2.WithOwner()
                                        .HasForeignKey("FatosConhecidosOfertaId")
                                        .HasConstraintName("fk_oferta_oferta_id");

                                    b2.OwnsOne("SbaCars.Inventory.Domain.Ofertas.Autoria", "AtualizadoPor", b3 =>
                                        {
                                            b3.Property<Guid>("BlocoFatoFatosConhecidosOfertaId")
                                                .HasColumnType("uuid")
                                                .HasColumnName("id");

                                            b3.Property<DateTimeOffset>("Em")
                                                .HasColumnType("timestamp with time zone")
                                                .HasColumnName("fato_origem_atualizado_por_em");

                                            b3.Property<string>("Nome")
                                                .IsRequired()
                                                .HasMaxLength(200)
                                                .HasColumnType("character varying(200)")
                                                .HasColumnName("fato_origem_atualizado_por_nome");

                                            b3.Property<string>("UsuarioId")
                                                .IsRequired()
                                                .HasMaxLength(200)
                                                .HasColumnType("character varying(200)")
                                                .HasColumnName("fato_origem_atualizado_por_usuario_id");

                                            b3.HasKey("BlocoFatoFatosConhecidosOfertaId");

                                            b3.ToTable("oferta", "inventory");

                                            b3.WithOwner()
                                                .HasForeignKey("BlocoFatoFatosConhecidosOfertaId")
                                                .HasConstraintName("fk_oferta_oferta_id");
                                        });

                                    b2.Navigation("AtualizadoPor")
                                        .IsRequired();
                                });

                            b1.Navigation("Condicao")
                                .IsRequired();

                            b1.Navigation("Historico")
                                .IsRequired();

                            b1.Navigation("Origem")
                                .IsRequired();
                        });

                    b.OwnsOne("SbaCars.Inventory.Domain.Ofertas.Autoria", "AtualizadaPor", b1 =>
                        {
                            b1.Property<Guid>("OfertaId")
                                .HasColumnType("uuid")
                                .HasColumnName("id");

                            b1.Property<DateTimeOffset>("Em")
                                .HasColumnType("timestamp with time zone")
                                .HasColumnName("atualizada_por_em");

                            b1.Property<string>("Nome")
                                .IsRequired()
                                .HasMaxLength(200)
                                .HasColumnType("character varying(200)")
                                .HasColumnName("atualizada_por_nome");

                            b1.Property<string>("UsuarioId")
                                .IsRequired()
                                .HasMaxLength(200)
                                .HasColumnType("character varying(200)")
                                .HasColumnName("atualizada_por_usuario_id");

                            b1.HasKey("OfertaId");

                            b1.ToTable("oferta", "inventory");

                            b1.WithOwner()
                                .HasForeignKey("OfertaId")
                                .HasConstraintName("fk_oferta_oferta_id");
                        });

                    b.OwnsOne("SbaCars.Inventory.Domain.Ofertas.Autoria", "CriadaPor", b1 =>
                        {
                            b1.Property<Guid>("OfertaId")
                                .HasColumnType("uuid")
                                .HasColumnName("id");

                            b1.Property<DateTimeOffset>("Em")
                                .HasColumnType("timestamp with time zone")
                                .HasColumnName("criada_por_em");

                            b1.Property<string>("Nome")
                                .IsRequired()
                                .HasMaxLength(200)
                                .HasColumnType("character varying(200)")
                                .HasColumnName("criada_por_nome");

                            b1.Property<string>("UsuarioId")
                                .IsRequired()
                                .HasMaxLength(200)
                                .HasColumnType("character varying(200)")
                                .HasColumnName("criada_por_usuario_id");

                            b1.HasKey("OfertaId");

                            b1.ToTable("oferta", "inventory");

                            b1.WithOwner()
                                .HasForeignKey("OfertaId")
                                .HasConstraintName("fk_oferta_oferta_id");
                        });

                    b.OwnsOne("SbaCars.Inventory.Domain.Ofertas.PrecoOficial", "PrecoOficial", b1 =>
                        {
                            b1.Property<Guid>("OfertaId")
                                .HasColumnType("uuid")
                                .HasColumnName("id");

                            b1.Property<string>("Moeda")
                                .IsRequired()
                                .HasMaxLength(3)
                                .HasColumnType("character varying(3)")
                                .HasColumnName("preco_moeda");

                            b1.Property<long>("ValorCentavos")
                                .HasColumnType("bigint")
                                .HasColumnName("preco_valor_centavos");

                            b1.HasKey("OfertaId");

                            b1.ToTable("oferta", "inventory");

                            b1.WithOwner()
                                .HasForeignKey("OfertaId")
                                .HasConstraintName("fk_oferta_oferta_id");

                            b1.OwnsOne("SbaCars.Inventory.Domain.Ofertas.Autoria", "DefinidoPor", b2 =>
                                {
                                    b2.Property<Guid>("PrecoOficialOfertaId")
                                        .HasColumnType("uuid")
                                        .HasColumnName("id");

                                    b2.Property<DateTimeOffset>("Em")
                                        .HasColumnType("timestamp with time zone")
                                        .HasColumnName("preco_definido_por_em");

                                    b2.Property<string>("Nome")
                                        .IsRequired()
                                        .HasMaxLength(200)
                                        .HasColumnType("character varying(200)")
                                        .HasColumnName("preco_definido_por_nome");

                                    b2.Property<string>("UsuarioId")
                                        .IsRequired()
                                        .HasMaxLength(200)
                                        .HasColumnType("character varying(200)")
                                        .HasColumnName("preco_definido_por_usuario_id");

                                    b2.HasKey("PrecoOficialOfertaId");

                                    b2.ToTable("oferta", "inventory");

                                    b2.WithOwner()
                                        .HasForeignKey("PrecoOficialOfertaId")
                                        .HasConstraintName("fk_oferta_oferta_id");
                                });

                            b1.Navigation("DefinidoPor")
                                .IsRequired();
                        });

                    b.OwnsOne("SbaCars.Inventory.Domain.Ofertas.Veiculo", "Veiculo", b1 =>
                        {
                            b1.Property<Guid>("OfertaId")
                                .HasColumnType("uuid")
                                .HasColumnName("id");

                            b1.Property<int?>("AnoFabricacao")
                                .HasColumnType("integer")
                                .HasColumnName("ano_fabricacao");

                            b1.Property<int?>("AnoModelo")
                                .HasColumnType("integer")
                                .HasColumnName("ano_modelo");

                            b1.Property<string>("Cambio")
                                .HasMaxLength(40)
                                .HasColumnType("character varying(40)")
                                .HasColumnName("cambio");

                            b1.Property<string>("Chassi")
                                .HasMaxLength(17)
                                .HasColumnType("character varying(17)")
                                .HasColumnName("chassi");

                            b1.Property<string>("Combustivel")
                                .HasMaxLength(40)
                                .HasColumnType("character varying(40)")
                                .HasColumnName("combustivel");

                            b1.Property<string>("Cor")
                                .HasMaxLength(80)
                                .HasColumnType("character varying(80)")
                                .HasColumnName("cor");

                            b1.Property<string>("Marca")
                                .HasMaxLength(120)
                                .HasColumnType("character varying(120)")
                                .HasColumnName("marca");

                            b1.Property<string>("Modelo")
                                .HasMaxLength(120)
                                .HasColumnType("character varying(120)")
                                .HasColumnName("modelo");

                            b1.Property<string>("Placa")
                                .HasMaxLength(10)
                                .HasColumnType("character varying(10)")
                                .HasColumnName("placa");

                            b1.Property<int?>("Quilometragem")
                                .HasColumnType("integer")
                                .HasColumnName("quilometragem");

                            b1.Property<string>("TipoVeiculo")
                                .IsRequired()
                                .HasMaxLength(30)
                                .HasColumnType("character varying(30)")
                                .HasColumnName("tipo_veiculo");

                            b1.Property<string>("Versao")
                                .HasMaxLength(120)
                                .HasColumnType("character varying(120)")
                                .HasColumnName("versao");

                            b1.HasKey("OfertaId");

                            b1.HasIndex("Placa")
                                .IsUnique()
                                .HasDatabaseName("ux_oferta_placa_ativa")
                                .HasFilter("situacao <> 'Retirada'");

                            b1.ToTable("oferta", "inventory");

                            b1.WithOwner()
                                .HasForeignKey("OfertaId")
                                .HasConstraintName("fk_oferta_oferta_id");

                            b1.OwnsOne("SbaCars.Inventory.Domain.Ofertas.Localizacao", "Localizacao", b2 =>
                                {
                                    b2.Property<Guid>("VeiculoOfertaId")
                                        .HasColumnType("uuid")
                                        .HasColumnName("id");

                                    b2.Property<string>("Cep")
                                        .HasMaxLength(8)
                                        .HasColumnType("character varying(8)")
                                        .HasColumnName("cep");

                                    b2.Property<string>("Cidade")
                                        .HasMaxLength(120)
                                        .HasColumnType("character varying(120)")
                                        .HasColumnName("cidade");

                                    b2.Property<string>("Uf")
                                        .HasMaxLength(2)
                                        .HasColumnType("character varying(2)")
                                        .HasColumnName("uf");

                                    b2.HasKey("VeiculoOfertaId");

                                    b2.ToTable("oferta", "inventory");

                                    b2.WithOwner()
                                        .HasForeignKey("VeiculoOfertaId")
                                        .HasConstraintName("fk_oferta_oferta_id");
                                });

                            b1.Navigation("Localizacao")
                                .IsRequired();
                        });

                    b.Navigation("AtualizadaPor")
                        .IsRequired();

                    b.Navigation("CriadaPor")
                        .IsRequired();

                    b.Navigation("Disponibilidade")
                        .IsRequired();

                    b.Navigation("Fatos")
                        .IsRequired();

                    b.Navigation("PrecoOficial");

                    b.Navigation("Veiculo")
                        .IsRequired();
                });

            modelBuilder.Entity("SbaCars.Inventory.Domain.Solicitacoes.Solicitacao", b =>
                {
                    b.OwnsOne("SbaCars.Inventory.Domain.Ofertas.Autoria", "AbertaPor", b1 =>
                        {
                            b1.Property<Guid>("SolicitacaoId")
                                .HasColumnType("uuid")
                                .HasColumnName("id");

                            b1.Property<DateTimeOffset>("Em")
                                .HasColumnType("timestamp with time zone")
                                .HasColumnName("aberta_por_em");

                            b1.Property<string>("Nome")
                                .IsRequired()
                                .HasMaxLength(200)
                                .HasColumnType("character varying(200)")
                                .HasColumnName("aberta_por_nome");

                            b1.Property<string>("UsuarioId")
                                .IsRequired()
                                .HasMaxLength(200)
                                .HasColumnType("character varying(200)")
                                .HasColumnName("aberta_por_usuario_id");

                            b1.HasKey("SolicitacaoId");

                            b1.ToTable("solicitacao", "inventory");

                            b1.WithOwner()
                                .HasForeignKey("SolicitacaoId")
                                .HasConstraintName("fk_solicitacao_solicitacao_id");
                        });

                    b.Navigation("AbertaPor")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
