/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/ofertas": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Listar ofertas do estoque
         * @description Retorna a lista paginada do estoque curado, com os filtros da tela de estoque.
         *     Todos os filtros são combináveis; filtros de lista (`situacao`, `disponibilidade`)
         *     aplicam `OR` entre seus valores e `AND` entre si.
         */
        get: operations["listarOfertas"];
        put?: never;
        /**
         * Cadastrar veículo
         * @description Cria o veículo e a oferta correspondente. **Aceita dados parciais** — este é o
         *     comportamento central do RF-01, não uma exceção. A oferta nasce sempre em
         *     `em-preparacao` e nenhum campo de critério mínimo é obrigatório aqui.
         *
         *     Somente `carro-seminovo` e `carro-usado` são aceitos em `tipoVeiculo` (RN-01);
         *     qualquer outro valor resulta em 422.
         */
        post: operations["cadastrarVeiculo"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/ofertas/{ofertaId}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Identificador da oferta curada. */
                ofertaId: components["parameters"]["OfertaId"];
            };
            cookie?: never;
        };
        /**
         * Obter detalhe da oferta
         * @description Retorna a oferta consolidada: veículo, fatos conhecidos, preço oficial vigente,
         *     disponibilidade, checklist de elegibilidade e solicitações pendentes. É a carga
         *     única da tela de detalhe — o frontend não deve compor essa tela com várias chamadas.
         */
        get: operations["obterOferta"];
        put?: never;
        post?: never;
        /**
         * Excluir oferta em preparação
         * @description Exclui definitivamente uma oferta. Permitido **somente** enquanto a situação for
         *     `em-preparacao`. Ofertas que já foram elegíveis são retiradas, nunca excluídas,
         *     para preservar o rastro operacional.
         */
        delete: operations["excluirOferta"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/ofertas/{ofertaId}/veiculo": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Identificador da oferta curada. */
                ofertaId: components["parameters"]["OfertaId"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /**
         * Atualizar dados do veículo
         * @description Atualiza parcialmente os dados do veículo. Campos ausentes no corpo permanecem
         *     inalterados; para limpar um campo, envie `null` explicitamente.
         *
         *     Se a oferta estiver `elegivel` e a alteração fizer com que ela deixe de cumprir um
         *     critério mínimo, a elegibilidade é **suspensa automaticamente** (RF-03). O cliente
         *     deve confirmar essa consequência enviando `confirmaSuspensao: true`; caso contrário
         *     a requisição falha com 409 e nada é alterado.
         */
        patch: operations["atualizarVeiculo"];
        trace?: never;
    };
    "/ofertas/{ofertaId}/preco": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Identificador da oferta curada. */
                ofertaId: components["parameters"]["OfertaId"];
            };
            cookie?: never;
        };
        get?: never;
        /**
         * Definir preço oficial inicial
         * @description Define o **primeiro** preço oficial da oferta, direto, sem passar pela fila de
         *     validação. Aceito somente enquanto não existe preço vigente.
         *
         *     A validação do Responsável existe para proteger um valor vigente de ser trocado sem
         *     revisão (RF-04). Quando ainda não há valor vigente, não há o que proteger — e exigir
         *     validação aqui obrigaria toda oferta a passar duas vezes pela fila antes de ser
         *     publicada, uma para o preço e outra para a elegibilidade, dobrando a carga sobre o
         *     papel que tem meta de SLA.
         *
         *     Havendo preço vigente, esta operação retorna 409: a alteração passa a ser
         *     `POST /ofertas/{ofertaId}/solicitacoes` com `tipo: preco`.
         */
        put: operations["definirPrecoInicial"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/ofertas/{ofertaId}/fatos": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Identificador da oferta curada. */
                ofertaId: components["parameters"]["OfertaId"];
            };
            cookie?: never;
        };
        get?: never;
        /**
         * Substituir fatos conhecidos
         * @description Substitui os três blocos de fatos de uma vez, espelhando o formulário completo da
         *     tela. Cada bloco é preenchido **ou** declarado indisponível com uma limitação — não
         *     existe terceiro estado válido para uma oferta elegível (RN-03, CM-6).
         *
         *     Um bloco com `indisponivel: true` exige `limitacaoDeclarada` não vazia e ignora
         *     descrição, fonte e evidência. Ausência de dado nunca impede a elegibilidade por si
         *     só; ausência de **declaração** impede (DP-03, RN-09).
         *
         *     Vale a mesma regra de suspensão do PATCH de veículo.
         */
        put: operations["substituirFatos"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/ofertas/{ofertaId}/evidencias/upload-url": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Identificador da oferta curada. */
                ofertaId: components["parameters"]["OfertaId"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Gerar URL de upload de evidência
         * @description Devolve uma URL S3 pré-autenticada de escrita. O cliente faz `PUT` direto no S3 com
         *     os headers indicados e depois referencia o `evidenciaId` ao salvar os fatos.
         *
         *     O bucket é privado: o objeto só é acessível por URL assinada, porque evidências de
         *     origem podem conter dado pessoal.
         */
        post: operations["gerarUrlUploadEvidencia"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/evidencias/{evidenciaId}/download-url": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Identificador da evidência. */
                evidenciaId: string;
            };
            cookie?: never;
        };
        /**
         * Gerar URL de leitura de evidência
         * @description Devolve uma URL S3 pré-autenticada de leitura, de vida curta. Nunca exponha a URL
         *     do objeto diretamente nem torne o bucket público.
         */
        get: operations["gerarUrlDownloadEvidencia"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/ofertas/{ofertaId}/disponibilidade": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Identificador da oferta curada. */
                ofertaId: components["parameters"]["OfertaId"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Alterar disponibilidade operacional
         * @description Aplica uma transição direta de disponibilidade, sem passar pela fila de validação.
         *     Transições aceitas aqui:
         *
         *     | De | Para |
         *     |---|---|
         *     | `disponivel` | `reservado` |
         *     | `disponivel` | `vendido` |
         *     | `reservado` | `disponivel` |
         *     | `reservado` | `vendido` |
         *
         *     A transição `vendido` → `disponivel` **não** é aceita aqui: exige validação e passa
         *     por `POST /ofertas/{ofertaId}/solicitacoes` com `tipo: reversao-venda` (RF-05).
         *
         *     Reservas nunca expiram sozinhas — liberar exige esta chamada explícita (DP-04).
         *     Alterar disponibilidade não altera a situação da oferta, e retirar a oferta não
         *     altera a disponibilidade (RN-05).
         */
        post: operations["alterarDisponibilidade"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/ofertas/{ofertaId}/solicitacoes": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Identificador da oferta curada. */
                ofertaId: components["parameters"]["OfertaId"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Abrir solicitação de validação
         * @description Abre uma solicitação pendente. O corpo é discriminado por `tipo`:
         *
         *     - `elegibilidade` — exige os 6 critérios mínimos atendidos, inclusive preço oficial
         *       vigente (RF-04). Também é o caminho para reincluir uma oferta `retirada` (QA-01).
         *     - `preco` — exige `novoPrecoCentavos`. O preço vigente continua valendo até a
         *       aprovação (RF-04).
         *     - `retirada` — ao aprovar, não altera a disponibilidade (RN-05).
         *     - `reversao-venda` — só a partir de `vendido`.
         *
         *     Enquanto houver solicitação pendente do mesmo tipo para a mesma oferta, uma nova
         *     é recusada com 409 (DUX-07).
         */
        post: operations["abrirSolicitacao"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/solicitacoes": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Listar solicitações
         * @description Fila de validação. Por padrão retorna apenas as pendentes, ordenadas da mais antiga
         *     para a mais recente — a ordem em que o SLA de um dia útil deve ser atacado.
         */
        get: operations["listarSolicitacoes"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/solicitacoes/pendentes/contagem": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Contar solicitações pendentes
         * @description Contagem leve para o badge da sidebar. Endpoint dedicado para não obrigar o cliente
         *     a paginar a fila inteira só para exibir um número.
         */
        get: operations["contarSolicitacoesPendentes"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/solicitacoes/{solicitacaoId}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Identificador da solicitação. */
                solicitacaoId: components["parameters"]["SolicitacaoId"];
            };
            cookie?: never;
        };
        /**
         * Obter detalhe da solicitação
         * @description Retorna tudo que a decisão exige: comparação entre vigente e proposto, justificativa
         *     do solicitante, contexto da oferta e o impacto textual da aprovação.
         */
        get: operations["obterSolicitacao"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/solicitacoes/{solicitacaoId}/aprovar": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Identificador da solicitação. */
                solicitacaoId: components["parameters"]["SolicitacaoId"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Aprovar solicitação
         * @description Aprova a solicitação e aplica a alteração correspondente.
         *
         *     **Quem abriu a solicitação não pode aprová-la** (DUX-08). A regra é do servidor, não
         *     da interface: a tentativa retorna 403 mesmo que a UI tenha permitido o clique.
         *
         *     Para alterações que afetam o catálogo, o evento correspondente é publicado nesta
         *     transação, de modo que D01 reflita a mudança em até uma hora.
         */
        post: operations["aprovarSolicitacao"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/solicitacoes/{solicitacaoId}/rejeitar": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Identificador da solicitação. */
                solicitacaoId: components["parameters"]["SolicitacaoId"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Rejeitar solicitação
         * @description Rejeita a solicitação. O estado vigente permanece intacto e o motivo volta ao
         *     operador (RF-02). A justificativa é obrigatória.
         */
        post: operations["rejeitarSolicitacao"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/ofertas-elegiveis": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Listar ofertas elegíveis para D01
         * @description Fornece ao catálogo público apenas as ofertas em situação `elegivel`, com os fatos,
         *     o preço oficial vigente, a localização e a disponibilidade. Ofertas retiradas,
         *     suspensas ou em preparação nunca aparecem aqui (RF-06).
         *
         *     Consumido por catalog-service (D01), não pelo backoffice. Suporta sincronização
         *     incremental por `atualizadoApos`, para que D01 reflita mudanças em até uma hora sem
         *     varrer o catálogo inteiro.
         *
         *     Autenticação por **client credentials**, não por token de operador: quem chama é um
         *     serviço, não uma pessoa.
         */
        get: operations["listarOfertasElegiveis"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * @description RFC 9457, no formato que o `GlobalExceptionHandler` já emite. O corpo nunca carrega
         *     stack trace nem nome de tipo interno.
         */
        ProblemDetails: {
            /**
             * Format: uri
             * @description URI que identifica o tipo do problema.
             * @example https://httpstatuses.io/422
             */
            type: string;
            /**
             * @description Resumo legível do tipo do problema.
             * @example Regra de negócio violada.
             */
            title: string;
            /**
             * @description Código HTTP repetido no corpo.
             * @example 422
             */
            status: number;
            /**
             * @description Explicação específica desta ocorrência.
             * @example Somente carros seminovos ou usados compõem o estoque curado.
             */
            detail?: string | null;
            /**
             * @description Path da requisição que falhou.
             * @example /api/ofertas
             */
            instance?: string | null;
            /**
             * @description Trace id W3C, o mesmo gravado no log do servidor.
             * @example 0af7651916cd43dd8448eb211c80319c
             */
            traceId?: string;
        };
        ProblemaSuspensao: components["schemas"]["ProblemDetails"] & {
            /**
             * @description Discriminador estável para o cliente reagir sem parsear texto.
             * @constant
             */
            codigo?: "suspensao-nao-confirmada";
            /** @description Critérios mínimos que deixariam de ser atendidos. */
            criteriosAfetados?: components["schemas"]["CodigoCriterio"][];
        };
        /**
         * @description Situação da oferta na curadoria.
         *     - `em-preparacao`: cadastro incompleto, nunca fornecido a D01.
         *     - `elegivel`: cumpre os critérios mínimos e é fornecido a D01.
         *     - `suspensa`: era elegível e deixou de cumprir um critério; volta só com nova validação.
         *     - `retirada`: fora da responsabilidade da operação; não afeta a disponibilidade.
         * @example elegivel
         * @enum {string}
         */
        SituacaoOferta: "em-preparacao" | "elegivel" | "suspensa" | "retirada";
        /**
         * @description Estado operacional do veículo.
         *     - `disponivel`: pode ser apresentado e reservado.
         *     - `reservado`: comprometido; nunca expira automaticamente.
         *     - `vendido`: venda concluída; voltar exige validação.
         * @example disponivel
         * @enum {string}
         */
        EstadoDisponibilidade: "disponivel" | "reservado" | "vendido";
        /**
         * @description Tipo da alteração que aguarda validação.
         *     - `elegibilidade`: tornar a oferta elegível para D01, ou reincluir uma retirada.
         *     - `preco`: alterar o preço oficial vigente.
         *     - `retirada`: retirar a oferta da curadoria.
         *     - `reversao-venda`: devolver uma oferta vendida para disponível.
         * @example preco
         * @enum {string}
         */
        TipoSolicitacao: "elegibilidade" | "preco" | "retirada" | "reversao-venda";
        /**
         * @description Ciclo de vida da solicitação.
         *     - `pendente`: aguardando decisão; o estado vigente continua valendo.
         *     - `aprovada`: decidida e aplicada.
         *     - `rejeitada`: decidida sem efeito, com motivo devolvido ao operador.
         * @example pendente
         * @enum {string}
         */
        StatusSolicitacao: "pendente" | "aprovada" | "rejeitada";
        /**
         * @description Categoria aceita no estoque curado. Somente estes dois valores existem nesta fase
         *     (RN-01) — motos e demais categorias estão fora do escopo.
         * @example carro-seminovo
         * @enum {string}
         */
        TipoVeiculo: "carro-seminovo" | "carro-usado";
        /**
         * @description Critérios mínimos de elegibilidade.
         *     - `identificacao`: placa preenchida.
         *     - `dados-basicos`: marca, modelo, versão, ano, quilometragem e câmbio.
         *     - `localizacao`: cidade e UF.
         *     - `preco-oficial`: existe preço vigente.
         *     - `disponibilidade`: estado de disponibilidade definido.
         *     - `transparencia-fatos`: cada bloco preenchido ou com limitação declarada.
         * @example transparencia-fatos
         * @enum {string}
         */
        CodigoCriterio: "identificacao" | "dados-basicos" | "localizacao" | "preco-oficial" | "disponibilidade" | "transparencia-fatos";
        /**
         * @description Bloco de fato conhecido, conforme as entidades do domain doc.
         * @example historico
         * @enum {string}
         */
        BlocoFatoTipo: "origem" | "condicao" | "historico";
        /**
         * @description Quem alterou e quando. Presente em todo valor sob curadoria, porque a operação
         *     precisa ver valor, data e responsável juntos.
         */
        Autoria: {
            /** Format: uuid */
            usuarioId: string;
            /** @example Ana Souza */
            nome: string;
            /**
             * Format: date-time
             * @example 2026-08-12T14:22:05Z
             */
            em: string;
        };
        Localizacao: {
            /** @example 13010-111 */
            cep?: string | null;
            /** @example Campinas */
            cidade?: string | null;
            /** @example SP */
            uf?: string | null;
        };
        /** @description Dados do carro. Todo campo é opcional enquanto a oferta está em preparação. */
        Veiculo: {
            /**
             * @description Placa no padrão brasileiro antigo ou Mercosul.
             * @example ABC1D23
             */
            placa?: string | null;
            /**
             * @description VIN de 17 caracteres.
             * @example 93HFC2650MZ204817
             */
            chassi?: string | null;
            tipoVeiculo: components["schemas"]["TipoVeiculo"];
            /** @example Honda */
            marca?: string | null;
            /** @example Civic */
            modelo?: string | null;
            /** @example EXL 2.0 */
            versao?: string | null;
            /** @example 2021 */
            anoFabricacao?: number | null;
            /** @example 2022 */
            anoModelo?: number | null;
            /** @example 48300 */
            quilometragem?: number | null;
            /** @example Prata */
            cor?: string | null;
            /** @example Flex */
            combustivel?: string | null;
            /** @example Automático */
            cambio?: string | null;
            localizacao?: components["schemas"]["Localizacao"];
        };
        /**
         * @description Corpo de cadastro. Apenas `tipoVeiculo` é obrigatório — os demais campos podem ser
         *     completados depois, e sua ausência apenas mantém a oferta em preparação.
         */
        VeiculoInput: {
            placa?: string | null;
            chassi?: string | null;
            tipoVeiculo: components["schemas"]["TipoVeiculo"];
            marca?: string | null;
            modelo?: string | null;
            versao?: string | null;
            anoFabricacao?: number | null;
            anoModelo?: number | null;
            quilometragem?: number | null;
            cor?: string | null;
            combustivel?: string | null;
            cambio?: string | null;
            localizacao?: components["schemas"]["Localizacao"];
        };
        VeiculoPatchInput: components["schemas"]["VeiculoInput"] & {
            /**
             * @description Confirma ciência de que a alteração suspenderá a elegibilidade. Sem `true`,
             *     uma alteração com esse efeito é recusada com 409 e nada é gravado.
             * @default false
             */
            confirmaSuspensao: boolean;
        };
        /** @description Arquivo anexado a um fato, armazenado em bucket privado. */
        Evidencia: {
            /** Format: uuid */
            evidenciaId: string;
            /** @example contrato-cessao-localiza.pdf */
            nomeArquivo: string;
            /** @example application/pdf */
            tipoConteudo: string;
            /** @example 1258291 */
            tamanhoBytes: number;
            /**
             * Format: date-time
             * @example 2026-08-10T11:04:33Z
             */
            enviadaEm: string;
        };
        /**
         * @description Um bloco de fato conhecido. Ou está preenchido, ou está declarado indisponível com
         *     uma limitação. As duas formas são válidas para elegibilidade; a ausência das duas
         *     não é (RN-03, CM-6).
         */
        BlocoFato: {
            tipo: components["schemas"]["BlocoFatoTipo"];
            /** @description Quando `true`, a informação não pôde ser obtida e há limitação declarada. */
            indisponivel: boolean;
            /** @example Veículo de frota corporativa, único proprietário pessoa jurídica. */
            descricao?: string | null;
            /** @example Contrato de cessão Localiza, 02/2026 */
            fonte?: string | null;
            evidencia?: components["schemas"]["Evidencia"] | null;
            /**
             * @description Obrigatória quando `indisponivel` é `true`. Exibida ao comprador em D01.
             * @example Não foi possível obter o histórico de sinistros junto às bases consultadas.
             */
            limitacaoDeclarada?: string | null;
            /**
             * @description Conveniência derivada: `true` quando o bloco tem conteúdo ou limitação
             *     declarada. Evita que o cliente reimplemente a regra do CM-6.
             */
            atendeTransparencia: boolean;
            atualizadoPor?: components["schemas"]["Autoria"] | null;
        };
        BlocoFatoInput: {
            indisponivel: boolean;
            descricao?: string | null;
            fonte?: string | null;
            /**
             * Format: uuid
             * @description Evidência previamente enviada ao S3.
             */
            evidenciaId?: string | null;
            /** @description Obrigatória quando `indisponivel` é `true`. */
            limitacaoDeclarada?: string | null;
        };
        FatosConhecidos: {
            origem: components["schemas"]["BlocoFato"];
            condicao: components["schemas"]["BlocoFato"];
            historico: components["schemas"]["BlocoFato"];
        };
        FatosInput: {
            origem: components["schemas"]["BlocoFatoInput"];
            condicao: components["schemas"]["BlocoFatoInput"];
            historico: components["schemas"]["BlocoFatoInput"];
            /**
             * @description Ver `VeiculoPatchInput.confirmaSuspensao`.
             * @default false
             */
            confirmaSuspensao: boolean;
        };
        UploadEvidenciaInput: {
            /** @example laudo-cautelar.pdf */
            nomeArquivo: string;
            /**
             * @description Tipos aceitos na Fase 1.
             * @example application/pdf
             * @enum {string}
             */
            tipoConteudo: "application/pdf" | "image/jpeg" | "image/png";
            /**
             * @description Máximo de 10 MiB.
             * @example 4194304
             */
            tamanhoBytes: number;
        };
        UploadEvidenciaResponse: {
            /**
             * Format: uuid
             * @description Referencie este id ao salvar os fatos.
             */
            evidenciaId: string;
            /**
             * Format: uri
             * @description URL pré-autenticada para `PUT` direto no S3.
             */
            uploadUrl: string;
            /** Format: date-time */
            expiraEm: string;
            /**
             * @description Headers que o `PUT` no S3 deve enviar exatamente como recebidos; a assinatura
             *     os cobre e omiti-los invalida o upload.
             */
            headersObrigatorios: {
                [key: string]: string;
            };
        };
        DownloadEvidenciaResponse: {
            /** Format: uri */
            downloadUrl: string;
            /** Format: date-time */
            expiraEm: string;
            nomeArquivo: string;
        };
        /**
         * @description Preço vigente. Enquanto houver solicitação de preço pendente, este valor continua
         *     sendo o válido (RF-04).
         */
        PrecoOficial: {
            /**
             * @description Valor em centavos de BRL. `8790000` equivale a R$ 87.900,00.
             * @example 8790000
             */
            valorCentavos: number;
            /** @constant */
            moeda: "BRL";
            definidoPor?: components["schemas"]["Autoria"] | null;
        };
        Disponibilidade: {
            estado: components["schemas"]["EstadoDisponibilidade"];
            /** Format: date-time */
            desde: string;
            alteradaPor?: components["schemas"]["Autoria"] | null;
            /**
             * @description Estados alcançáveis por chamada direta a partir do estado atual. Não inclui
             *     `disponivel` quando o estado é `vendido`, porque essa transição exige validação.
             */
            transicoesPermitidas: components["schemas"]["EstadoDisponibilidade"][];
        };
        CriterioElegibilidade: {
            codigo: components["schemas"]["CodigoCriterio"];
            atendido: boolean;
            /**
             * @description O que falta, em texto exibível quando `atendido` é `false`.
             * @example Condição sem limitação declarada
             */
            pendencia?: string | null;
        };
        ChecklistElegibilidade: {
            /** @example 5 */
            atendidos: number;
            /** @example 6 */
            total: number;
            criterios: components["schemas"]["CriterioElegibilidade"][];
            /**
             * @description `true` quando todos os critérios são atendidos e não há solicitação de
             *     elegibilidade pendente. É a única fonte para habilitar o botão na interface.
             */
            podeSolicitarElegibilidade: boolean;
        };
        PendenciaResumo: {
            /** Format: uuid */
            solicitacaoId: string;
            tipo: components["schemas"]["TipoSolicitacao"];
            /**
             * @description Transição em texto, pronta para exibir.
             * @example R$ 87.900,00 → R$ 84.500,00
             */
            resumoAlteracao?: string | null;
            /** Format: date-time */
            abertaEm: string;
            abertaPor: components["schemas"]["Autoria"];
        };
        /** @description Linha da lista de estoque. */
        OfertaResumo: {
            /** Format: uuid */
            ofertaId: string;
            /** @example ABC1D23 */
            placa?: string | null;
            /**
             * @description Marca, modelo e versão concatenados para exibição.
             * @example Honda Civic EXL 2.0
             */
            descricaoVeiculo?: string | null;
            /** @example 2021 */
            anoFabricacao?: number | null;
            /** @example 2022 */
            anoModelo?: number | null;
            /** @example 48300 */
            quilometragem?: number | null;
            localizacao?: components["schemas"]["Localizacao"];
            /** @example 8790000 */
            precoOficialCentavos?: number | null;
            situacao: components["schemas"]["SituacaoOferta"];
            disponibilidade: components["schemas"]["EstadoDisponibilidade"];
            /** @description Tipos de solicitação pendentes. Vazio quando não há nenhuma. */
            pendencias: components["schemas"]["TipoSolicitacao"][];
            /** Format: date-time */
            atualizadoEm: string;
        };
        /** @description Carga completa da tela de detalhe da oferta. */
        OfertaDetalhe: {
            /** Format: uuid */
            ofertaId: string;
            situacao: components["schemas"]["SituacaoOferta"];
            /**
             * @description Preenchido apenas quando a situação é `suspensa`.
             * @example A remoção da fonte do bloco Condição fez a oferta deixar de cumprir os critérios mínimos.
             */
            motivoSuspensao?: string | null;
            /** Format: date-time */
            suspensaEm?: string | null;
            veiculo: components["schemas"]["Veiculo"];
            fatos: components["schemas"]["FatosConhecidos"];
            precoOficial?: components["schemas"]["PrecoOficial"] | null;
            disponibilidade: components["schemas"]["Disponibilidade"];
            elegibilidade: components["schemas"]["ChecklistElegibilidade"];
            pendencias: components["schemas"]["PendenciaResumo"][];
            /** Format: date-time */
            criadaEm: string;
            /** Format: date-time */
            atualizadoEm: string;
        };
        /**
         * @description Projeção fornecida a D01. Não expõe solicitações, checklist nem qualquer dado do
         *     fluxo interno de validação — apenas o que o catálogo público precisa apresentar.
         */
        OfertaElegivel: {
            /** Format: uuid */
            ofertaId: string;
            veiculo: components["schemas"]["Veiculo"];
            fatos: components["schemas"]["FatosConhecidos"];
            precoOficial: components["schemas"]["PrecoOficial"];
            disponibilidade: components["schemas"]["EstadoDisponibilidade"];
            /** Format: date-time */
            atualizadoEm: string;
        };
        /** @description Linha da fila de validação. */
        SolicitacaoResumo: {
            /** Format: uuid */
            solicitacaoId: string;
            /** Format: uuid */
            ofertaId: string;
            /** @example ABC1D23 */
            placa?: string | null;
            /** @example Honda Civic EXL 2.0 */
            descricaoVeiculo?: string | null;
            tipo: components["schemas"]["TipoSolicitacao"];
            status: components["schemas"]["StatusSolicitacao"];
            /**
             * @description Estado atual em texto exibível.
             * @example Em preparação
             */
            valorVigente?: string | null;
            /**
             * @description Estado proposto em texto exibível.
             * @example Elegível
             */
            valorProposto?: string | null;
            /** Format: date-time */
            abertaEm: string;
            abertaPor: components["schemas"]["Autoria"];
            /**
             * @description `true` quando a solicitação está pendente há mais de um dia útil. Calculado no
             *     servidor para que a fila não dependa do relógio do cliente.
             */
            foraDoSla: boolean;
        };
        SolicitacaoDetalhe: components["schemas"]["SolicitacaoResumo"] & {
            /**
             * @description Texto integral escrito por quem abriu a solicitação.
             * @example Cadastro completo, laudo de origem anexado e limitação de histórico declarada.
             */
            justificativa: string;
            /**
             * @description Presente somente quando o tipo é `preco`.
             * @example 8450000
             */
            novoPrecoCentavos?: number | null;
            /** @description Presente somente quando o tipo é `elegibilidade`. */
            elegibilidadeProposta?: components["schemas"]["ChecklistElegibilidade"] | null;
            contextoOferta?: components["schemas"]["ContextoOferta"];
            /**
             * @description Consequência da aprovação em texto pronto para exibir, gerada pelo servidor
             *     para que a interface não recomponha a regra.
             * @example Ao aprovar, esta oferta passa a ser fornecida ao catálogo público em até 1 hora.
             */
            impactoAoAprovar: string;
            /** @description Presente somente quando o status não é `pendente`. */
            decisao?: components["schemas"]["Decisao"] | null;
            /**
             * @description `false` quando o usuário autenticado abriu a solicitação. A interface usa
             *     isso para desabilitar os botões; o servidor bloqueia de qualquer forma.
             */
            podeDecidir?: boolean;
        };
        /** @description Resumo somente-leitura da oferta, para decidir sem trocar de tela. */
        ContextoOferta: {
            situacao: components["schemas"]["SituacaoOferta"];
            disponibilidade: components["schemas"]["EstadoDisponibilidade"];
            precoOficial?: components["schemas"]["PrecoOficial"] | null;
            localizacao?: components["schemas"]["Localizacao"];
            /** @description Blocos de fato que estão declarados como indisponíveis. */
            blocosComLimitacao?: components["schemas"]["BlocoFatoTipo"][];
        };
        Decisao: {
            /** @enum {string} */
            status: "aprovada" | "rejeitada";
            /** Format: date-time */
            decididaEm: string;
            decididaPor: components["schemas"]["Autoria"];
            /**
             * @description Obrigatória na rejeição, opcional na aprovação.
             * @example Falta declarar a limitação do bloco Condição antes de publicar.
             */
            justificativa?: string | null;
        };
        AbrirSolicitacaoInput: components["schemas"]["SolicitacaoElegibilidadeInput"] | components["schemas"]["SolicitacaoPrecoInput"] | components["schemas"]["SolicitacaoRetiradaInput"] | components["schemas"]["SolicitacaoReversaoVendaInput"];
        SolicitacaoElegibilidadeInput: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            tipo: "elegibilidade";
            justificativa: string;
        };
        SolicitacaoPrecoInput: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            tipo: "preco";
            /**
             * @description Novo valor em centavos de BRL.
             * @example 8450000
             */
            novoPrecoCentavos: number;
            justificativa: string;
        };
        SolicitacaoRetiradaInput: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            tipo: "retirada";
            justificativa: string;
        };
        SolicitacaoReversaoVendaInput: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            tipo: "reversao-venda";
            justificativa: string;
        };
        DefinirPrecoInicialInput: {
            /**
             * @description Preço oficial em centavos de BRL. `8790000` equivale a R$ 87.900,00.
             * @example 8790000
             */
            valorCentavos: number;
        };
        AprovarSolicitacaoInput: {
            /** @description Comentário opcional do responsável, registrado com a decisão. */
            observacao?: string | null;
        };
        RejeitarSolicitacaoInput: {
            /**
             * @description Obrigatória (RF-02). É devolvida ao operador como motivo da rejeição.
             * @example Falta declarar a limitação do bloco Condição antes de publicar.
             */
            justificativa: string;
        };
        AlterarDisponibilidadeInput: {
            novoEstado: components["schemas"]["EstadoDisponibilidade"];
            /**
             * @description Contexto opcional da transição. Ao encerrar uma reserva, use-o para registrar o
             *     motivo da liberação.
             */
            observacao?: string | null;
        };
        /**
         * @description Envelope de paginação idêntico ao `PagedResult<T>` já usado no backend, para que a
         *     serialização não precise de adaptador.
         */
        PaginacaoBase: {
            /** @example 1 */
            page: number;
            /** @example 20 */
            pageSize: number;
            /** @example 142 */
            totalCount: number;
            /** @example 8 */
            totalPages: number;
            hasNextPage: boolean;
            hasPreviousPage: boolean;
        };
        OfertaResumoPaginado: components["schemas"]["PaginacaoBase"] & {
            items: components["schemas"]["OfertaResumo"][];
        };
        SolicitacaoResumoPaginado: components["schemas"]["PaginacaoBase"] & {
            items: components["schemas"]["SolicitacaoResumo"][];
        };
        OfertaElegivelPaginado: components["schemas"]["PaginacaoBase"] & {
            items: components["schemas"]["OfertaElegivel"][];
        };
        ContagemPendentes: {
            /** @example 7 */
            total: number;
            /** @description Contagem por tipo de solicitação. */
            porTipo: {
                [key: string]: number;
            };
            /**
             * @description Quantas das pendentes já passaram de um dia útil.
             * @example 2
             */
            foraDoSla: number;
        };
    };
    responses: {
        /** @description Requisição malformada ou parâmetros inválidos. */
        RequisicaoInvalida: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["ProblemDetails"];
            };
        };
        /** @description Token ausente, expirado ou inválido. */
        NaoAutenticado: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["ProblemDetails"];
            };
        };
        /** @description Autenticado, mas sem a permissão exigida. */
        SemPermissao: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["ProblemDetails"];
            };
        };
        /** @description Recurso não encontrado. */
        NaoEncontrado: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["ProblemDetails"];
            };
        };
        /**
         * @description Regra de negócio do domínio violada. Ex.: tipo de veículo fora de carro seminovo ou
         *     usado (RN-01), transição de disponibilidade inválida, critério mínimo ausente.
         */
        RegraDeNegocioViolada: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["ProblemDetails"];
            };
        };
        /**
         * @description A alteração suspenderia a elegibilidade e `confirmaSuspensao` não foi enviado como
         *     `true`. Nada foi alterado.
         */
        SuspensaoNaoConfirmada: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["ProblemaSuspensao"];
            };
        };
        /** @description Erro inesperado. O `traceId` correlaciona com o log do servidor. */
        ErroInterno: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["ProblemDetails"];
            };
        };
    };
    parameters: {
        /** @description Página, 1-based. Valores menores que 1 são normalizados para 1. */
        Page: number;
        /** @description Itens por página. Máximo de 100; valores maiores são normalizados. */
        PageSize: number;
        /** @description Identificador da oferta curada. */
        OfertaId: string;
        /** @description Identificador da solicitação. */
        SolicitacaoId: string;
    };
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    listarOfertas: {
        parameters: {
            query?: {
                /** @description Página, 1-based. Valores menores que 1 são normalizados para 1. */
                page?: components["parameters"]["Page"];
                /** @description Itens por página. Máximo de 100; valores maiores são normalizados. */
                pageSize?: components["parameters"]["PageSize"];
                /** @description Busca livre por placa, marca ou modelo. Mínimo de 2 caracteres. */
                busca?: string;
                /** @description Filtra por uma ou mais situações da oferta. */
                situacao?: components["schemas"]["SituacaoOferta"][];
                /** @description Filtra por um ou mais estados de disponibilidade. */
                disponibilidade?: components["schemas"]["EstadoDisponibilidade"][];
                /** @description Sigla da unidade federativa da localização do veículo. */
                uf?: string;
                /**
                 * @description Campo e direção de ordenação. Padrão `atualizadoEm:desc`, que é a ordem em que
                 *     a operação espera ver o que mudou por último.
                 */
                ordenarPor?: "atualizadoEm:desc" | "atualizadoEm:asc" | "precoOficialCentavos:desc" | "precoOficialCentavos:asc" | "veiculo:asc";
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Página de ofertas retornada. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OfertaResumoPaginado"];
                };
            };
            400: components["responses"]["RequisicaoInvalida"];
            401: components["responses"]["NaoAutenticado"];
            403: components["responses"]["SemPermissao"];
            500: components["responses"]["ErroInterno"];
        };
    };
    cadastrarVeiculo: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["VeiculoInput"];
            };
        };
        responses: {
            /** @description Oferta criada em preparação. */
            201: {
                headers: {
                    /** @description URI da oferta criada. */
                    Location?: string;
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OfertaDetalhe"];
                };
            };
            400: components["responses"]["RequisicaoInvalida"];
            401: components["responses"]["NaoAutenticado"];
            403: components["responses"]["SemPermissao"];
            /** @description Já existe uma oferta ativa para esta placa. */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
            422: components["responses"]["RegraDeNegocioViolada"];
            500: components["responses"]["ErroInterno"];
        };
    };
    obterOferta: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Identificador da oferta curada. */
                ofertaId: components["parameters"]["OfertaId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Oferta encontrada. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OfertaDetalhe"];
                };
            };
            401: components["responses"]["NaoAutenticado"];
            403: components["responses"]["SemPermissao"];
            404: components["responses"]["NaoEncontrado"];
            500: components["responses"]["ErroInterno"];
        };
    };
    excluirOferta: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Identificador da oferta curada. */
                ofertaId: components["parameters"]["OfertaId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Oferta excluída. */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            401: components["responses"]["NaoAutenticado"];
            403: components["responses"]["SemPermissao"];
            404: components["responses"]["NaoEncontrado"];
            422: components["responses"]["RegraDeNegocioViolada"];
            500: components["responses"]["ErroInterno"];
        };
    };
    atualizarVeiculo: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Identificador da oferta curada. */
                ofertaId: components["parameters"]["OfertaId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["VeiculoPatchInput"];
            };
        };
        responses: {
            /** @description Veículo atualizado. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OfertaDetalhe"];
                };
            };
            400: components["responses"]["RequisicaoInvalida"];
            401: components["responses"]["NaoAutenticado"];
            403: components["responses"]["SemPermissao"];
            404: components["responses"]["NaoEncontrado"];
            409: components["responses"]["SuspensaoNaoConfirmada"];
            422: components["responses"]["RegraDeNegocioViolada"];
            500: components["responses"]["ErroInterno"];
        };
    };
    definirPrecoInicial: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Identificador da oferta curada. */
                ofertaId: components["parameters"]["OfertaId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DefinirPrecoInicialInput"];
            };
        };
        responses: {
            /** @description Preço oficial definido. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OfertaDetalhe"];
                };
            };
            400: components["responses"]["RequisicaoInvalida"];
            401: components["responses"]["NaoAutenticado"];
            403: components["responses"]["SemPermissao"];
            404: components["responses"]["NaoEncontrado"];
            /** @description Já existe preço vigente. Use uma solicitação de alteração de preço. */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
            422: components["responses"]["RegraDeNegocioViolada"];
            500: components["responses"]["ErroInterno"];
        };
    };
    substituirFatos: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Identificador da oferta curada. */
                ofertaId: components["parameters"]["OfertaId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["FatosInput"];
            };
        };
        responses: {
            /** @description Fatos substituídos. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OfertaDetalhe"];
                };
            };
            400: components["responses"]["RequisicaoInvalida"];
            401: components["responses"]["NaoAutenticado"];
            403: components["responses"]["SemPermissao"];
            404: components["responses"]["NaoEncontrado"];
            409: components["responses"]["SuspensaoNaoConfirmada"];
            422: components["responses"]["RegraDeNegocioViolada"];
            500: components["responses"]["ErroInterno"];
        };
    };
    gerarUrlUploadEvidencia: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Identificador da oferta curada. */
                ofertaId: components["parameters"]["OfertaId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UploadEvidenciaInput"];
            };
        };
        responses: {
            /** @description URL de upload gerada. */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UploadEvidenciaResponse"];
                };
            };
            400: components["responses"]["RequisicaoInvalida"];
            401: components["responses"]["NaoAutenticado"];
            403: components["responses"]["SemPermissao"];
            404: components["responses"]["NaoEncontrado"];
            /** @description Arquivo excede o tamanho máximo permitido. */
            413: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
            /** @description Tipo de conteúdo não aceito. */
            415: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
            500: components["responses"]["ErroInterno"];
        };
    };
    gerarUrlDownloadEvidencia: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Identificador da evidência. */
                evidenciaId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description URL de leitura gerada. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DownloadEvidenciaResponse"];
                };
            };
            401: components["responses"]["NaoAutenticado"];
            403: components["responses"]["SemPermissao"];
            404: components["responses"]["NaoEncontrado"];
            500: components["responses"]["ErroInterno"];
        };
    };
    alterarDisponibilidade: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Identificador da oferta curada. */
                ofertaId: components["parameters"]["OfertaId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AlterarDisponibilidadeInput"];
            };
        };
        responses: {
            /** @description Disponibilidade alterada. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OfertaDetalhe"];
                };
            };
            400: components["responses"]["RequisicaoInvalida"];
            401: components["responses"]["NaoAutenticado"];
            403: components["responses"]["SemPermissao"];
            404: components["responses"]["NaoEncontrado"];
            422: components["responses"]["RegraDeNegocioViolada"];
            500: components["responses"]["ErroInterno"];
        };
    };
    abrirSolicitacao: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Identificador da oferta curada. */
                ofertaId: components["parameters"]["OfertaId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AbrirSolicitacaoInput"];
            };
        };
        responses: {
            /** @description Solicitação aberta e pendente de validação. */
            201: {
                headers: {
                    /** @description URI da solicitação criada. */
                    Location?: string;
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SolicitacaoDetalhe"];
                };
            };
            400: components["responses"]["RequisicaoInvalida"];
            401: components["responses"]["NaoAutenticado"];
            403: components["responses"]["SemPermissao"];
            404: components["responses"]["NaoEncontrado"];
            /** @description Já existe solicitação pendente deste tipo para esta oferta. */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
            422: components["responses"]["RegraDeNegocioViolada"];
            500: components["responses"]["ErroInterno"];
        };
    };
    listarSolicitacoes: {
        parameters: {
            query?: {
                /** @description Página, 1-based. Valores menores que 1 são normalizados para 1. */
                page?: components["parameters"]["Page"];
                /** @description Itens por página. Máximo de 100; valores maiores são normalizados. */
                pageSize?: components["parameters"]["PageSize"];
                /** @description Filtra por status. Padrão `pendente`. */
                status?: components["schemas"]["StatusSolicitacao"];
                /** @description Filtra por um ou mais tipos de solicitação. */
                tipo?: components["schemas"]["TipoSolicitacao"][];
                /** @description Campo e direção de ordenação. */
                ordenarPor?: "abertaEm:asc" | "abertaEm:desc" | "decididaEm:desc";
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Página de solicitações retornada. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SolicitacaoResumoPaginado"];
                };
            };
            400: components["responses"]["RequisicaoInvalida"];
            401: components["responses"]["NaoAutenticado"];
            403: components["responses"]["SemPermissao"];
            500: components["responses"]["ErroInterno"];
        };
    };
    contarSolicitacoesPendentes: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Contagem retornada. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ContagemPendentes"];
                };
            };
            401: components["responses"]["NaoAutenticado"];
            403: components["responses"]["SemPermissao"];
            500: components["responses"]["ErroInterno"];
        };
    };
    obterSolicitacao: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Identificador da solicitação. */
                solicitacaoId: components["parameters"]["SolicitacaoId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Solicitação encontrada. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SolicitacaoDetalhe"];
                };
            };
            401: components["responses"]["NaoAutenticado"];
            403: components["responses"]["SemPermissao"];
            404: components["responses"]["NaoEncontrado"];
            500: components["responses"]["ErroInterno"];
        };
    };
    aprovarSolicitacao: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Identificador da solicitação. */
                solicitacaoId: components["parameters"]["SolicitacaoId"];
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["AprovarSolicitacaoInput"];
            };
        };
        responses: {
            /** @description Solicitação aprovada e alteração aplicada. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SolicitacaoDetalhe"];
                };
            };
            401: components["responses"]["NaoAutenticado"];
            /** @description Sem a permissão `estoque:validar`, ou tentativa de aprovar a própria solicitação. */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
            404: components["responses"]["NaoEncontrado"];
            /** @description Solicitação já decidida. */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
            422: components["responses"]["RegraDeNegocioViolada"];
            500: components["responses"]["ErroInterno"];
        };
    };
    rejeitarSolicitacao: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Identificador da solicitação. */
                solicitacaoId: components["parameters"]["SolicitacaoId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RejeitarSolicitacaoInput"];
            };
        };
        responses: {
            /** @description Solicitação rejeitada. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SolicitacaoDetalhe"];
                };
            };
            400: components["responses"]["RequisicaoInvalida"];
            401: components["responses"]["NaoAutenticado"];
            403: components["responses"]["SemPermissao"];
            404: components["responses"]["NaoEncontrado"];
            /** @description Solicitação já decidida. */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
            422: components["responses"]["RegraDeNegocioViolada"];
            500: components["responses"]["ErroInterno"];
        };
    };
    listarOfertasElegiveis: {
        parameters: {
            query?: {
                /** @description Página, 1-based. Valores menores que 1 são normalizados para 1. */
                page?: components["parameters"]["Page"];
                /** @description Itens por página. Máximo de 100; valores maiores são normalizados. */
                pageSize?: components["parameters"]["PageSize"];
                /** @description Retorna apenas ofertas alteradas após este instante. */
                atualizadoApos?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Página de ofertas elegíveis retornada. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OfertaElegivelPaginado"];
                };
            };
            400: components["responses"]["RequisicaoInvalida"];
            401: components["responses"]["NaoAutenticado"];
            403: components["responses"]["SemPermissao"];
            500: components["responses"]["ErroInterno"];
        };
    };
}
